replicaCount: 1

image:
  repository: microwave1005/fraud-detection-api
  tag: latest 
  pullPolicy: IfNotPresent

service:
  name: fraud-detection-api
  namespace: api
  ports:
    http: 8000
    metrics: 8001

env:
  S3_ENDPOINT: "minio.minio.svc.cluster.local:9000"
  EVIDENTLY_WORKSPACE: "http://35.202.139.205:8000/"
  FSSPEC_S3_ENDPOINT_URL: "http://minio.minio.svc.cluster.local:9000"

secrets:
  name: minio-creds
  accessKeyIdKey: access_key
  secretAccessKeyKey: secret_key

ingress:
  enabled: false
  ingressClassName: nginx
  annotations: {}
  rules: []
