transaction_schema = {
    "type": "record",
    "namespace": "com.example",
    "name": "Transaction",
    "fields": [
        {"name": "User", "type": "long"},
        {"name": "Card", "type": "long"},
        {"name": "Year", "type": "int"},
        {"name": "Month", "type": "int"},
        {"name": "Day", "type": "int"},
        {"name": "Time", "type": "string"},
        {"name": "Amount", "type": "string"},
        {"name": "Use Chip", "type": ["null", "string"], "default": None},
        {"name": "Merchant Name", "type": ["null", "long"], "default": None},
        {"name": "Merchant City", "type": ["null", "string"], "default": None},
        {"name": "Merchant State", "type": ["null", "string"], "default": None},
        {"name": "Zip", "type": ["null", "double"], "default": None},
        {"name": "MCC", "type": "int"},
        {"name": "Errors?", "type": ["null", "string"], "default": None},
        {"name": "Is Fraud?", "type": "string"},
    ],
}

user_schema = {
    "type": "record",
    "namespace": "com.example",
    "name": "User",
    "fields": [
        {"name": "idx", "type": "int"},
        {"name": "Person", "type": "string"},
        {"name": "Current Age", "type": "int"},
        {"name": "Retirement Age", "type": "int"},
        {"name": "Birth Year", "type": "int"},
        {"name": "Birth Month", "type": "int"},
        {"name": "Gender", "type": "string"},
        {"name": "Address", "type": "string"},
        {"name": "Apartment", "type": ["null", "double"], "default": None},
        {"name": "City", "type": "string"},
        {"name": "State", "type": "string"},
        {"name": "Zipcode", "type": "int"},
        {"name": "Latitude", "type": "double"},
        {"name": "Longitude", "type": "double"},
        {"name": "Per Capita Income - Zipcode", "type": "string"},
        {"name": "Yearly Income - Person", "type": "string"},
        {"name": "Total Debt", "type": "string"},
        {"name": "FICO Score", "type": "int"},
        {"name": "Num Credit Cards", "type": "int"},
    ],
}


card_schema = {
    "type": "record",
    "namespace": "com.example",
    "name": "Card",
    "fields": [
        {"name": "User", "type": "long"},
        {"name": "CARD INDEX", "type": "long"},
        {"name": "Card Brand", "type": "string"},
        {"name": "Card Type", "type": "string"},
        {"name": "Card Number", "type": "long"},
        {"name": "Expires", "type": "string"},
        {"name": "CVV", "type": "int"},
        {"name": "Has Chip", "type": "string"},
        {"name": "Cards Issued", "type": "long"},
        {"name": "Credit Limit", "type": "string"},
        {"name": "Acct Open Date", "type": "string"},
        {"name": "Year PIN last Changed", "type": "int"},
        {"name": "Card on Dark Web", "type": "string"},
    ],
}
