FROM python:3.11.11-slim

WORKDIR /app

COPY ./src/client ./client
COPY ./requirements_api.txt ./requirements_api.txt

RUN pip install -r ./requirements_api.txt

EXPOSE 8000

WORKDIR /app/client

CMD ["uvicorn", "infer:app", "--host", "0.0.0.0", "--port", "8000"]
