FROM confluentinc/cp-kafka-connect:7.0.9 AS cp

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.5.21
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-avro-converter:7.0.9
RUN wget https://github.com/ClickHouse/clickhouse-kafka-connect/releases/download/v1.3.2/clickhouse-kafka-connect-v1.3.2.zip \
    && unzip clickhouse-kafka-connect-v1.3.2.zip -d /tmp/clickhouse-connector

FROM quay.io/strimzi/kafka:0.46.0-kafka-4.0.0
USER root:root

RUN mkdir -p /opt/kafka/plugins/kafka-connect-s3/
RUN mkdir -p /opt/kafka/plugins/kafka-connect-avro-converter/
RUN mkdir -p /opt/kafka/plugins/clickhouse-kafka-connect/

COPY --from=cp /usr/share/confluent-hub-components/confluentinc-kafka-connect-s3/ /opt/kafka/plugins/kafka-connect-s3/
COPY --from=cp /usr/share/confluent-hub-components/confluentinc-kafka-connect-avro-converter/ /opt/kafka/plugins/kafka-connect-avro-converter/
COPY --from=cp /tmp/clickhouse-connector /opt/kafka/plugins/clickhouse-kafka-connect/

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws

RUN mkdir -p /home/user/.aws && chown -R 1001:1001 /home/user/.aws

USER 1001
