replicaCount: 1

image:
  repository: dbeaver/cloudbeaver
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80           # Service expose ra cho Ingress
  targetPort: 8978   # CloudBeaver listen trong container

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: dbeaver.ducdh.com   # Đổi về domain thật nếu cần
  path: /
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
