apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-streamlit
  labels:
    app: streamlit
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: streamlit
    release: {{ .Release.Name }}
