apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ .Values.kafkaConnector.name }}
  namespace: {{ .Values.general.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafkaConnect.name }}
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: {{ .Values.kafkaConnector.tasksMax }}
  config:
    topics: {{ .Values.kafkaConnector.config.topics }}
    s3.credentials.provider.class: "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
    s3.bucket.name: {{ .Values.kafkaConnector.config.s3BucketName }}
    s3.region: "us-west-1"
    store.url: {{ .Values.kafkaConnector.config.storeUrl }}
    s3.part.size: {{ .Values.kafkaConnector.config.s3PartSize }} 
    flush.size: {{ .Values.kafkaConnector.config.s3FlushSize }} 
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    format.class: "io.confluent.connect.s3.format.avro.AvroFormat"
    schema.compatibility: "NONE"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: {{ .Values.kafkaConnector.config.schemaRegistryUrl }}