apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: minio-sink-connector-transaction
  namespace: kafka
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    topics: "transaction-topic"
    s3.credentials.provider.class: "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
    s3.bucket.name: "stream-bucket"
    s3.region: "us-west-1"
    store.url: "http://minio.minio.svc.cluster.local:9000"
    s3.part.size: 5242880 
    flush.size: 243869 
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    format.class: "io.confluent.connect.s3.format.avro.AvroFormat"
    schema.compatibility: "NONE"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schemas.enable: true
    value.converter.schema.registry.url: "http://schema-registry-svc:8081"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: minio-sink-connector-user
  namespace: kafka
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    topics: "user-topic"
    s3.credentials.provider.class: "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
    s3.bucket.name: "stream-bucket"
    s3.region: "us-west-1"
    store.url: "http://minio.minio.svc.cluster.local:9000"
    s3.part.size: 5242880         
    flush.size: 1000
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    format.class: "io.confluent.connect.s3.format.avro.AvroFormat"
    schema.compatibility: "NONE"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schemas.enable: true
    value.converter.schema.registry.url: "http://schema-registry-svc:8081"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: minio-sink-connector-card
  namespace: kafka
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    topics: "card-topic"
    s3.credentials.provider.class: "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
    s3.bucket.name: "stream-bucket"
    s3.region: "us-west-1"
    store.url: "http://minio.minio.svc.cluster.local:9000"
    s3.part.size: 5242880         
    flush.size: 1000              
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    format.class: "io.confluent.connect.s3.format.avro.AvroFormat"
    schema.compatibility: "NONE"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    key.converter.schemas.enable: false
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schemas.enable: true
    value.converter.schema.registry.url: "http://schema-registry-svc:8081"
