apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.env.KAFKA_BROKER | quote }}
            - name: KAFKA_TOPIC
              value: {{ .Values.env.KAFKA_TOPIC | quote }}
            - name: SCHEMA_REGISTRY_URL
              value: {{ .Values.env.SCHEMA_REGISTRY_URL | quote }}
            - name: SLACK_CHANNEL
              value: {{ .Values.env.SLACK_CHANNEL | quote }}
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.slackSecretName }}
                  key: {{ .Values.secrets.slackBotTokenKey }}
          ports:
            - containerPort: 8000
