apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.slackSecretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{ .Values.secrets.slackBotTokenKey }}: {{ .Values.secrets.slackBotToken | quote }}
