apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      name: http
    - port: {{ .Values.service.ports.metrics }}
      targetPort: {{ .Values.service.ports.metrics }}
      name: metrics